[package]
name = "static-resource"
version = "0.2.0"
edition = "2024"

[dependencies]
hazarc = { version = "0.2.0", optional = true }
paste = { version = "1.0.15", optional = true }
tokio = { version = "1", features = ["rt"], optional = true }
tracing = { version = "0.1.44", optional = true }

[features]
reload = ["dep:hazarc"]
bundle = ["dep:tokio", "dep:paste"]
tracing = ["dep:tracing"]

[dev-dependencies]
divan = "0.1.21"
tokio = { version = "1", features = ["rt", "signal", "macros"] }

[[bench]]
name = "perf"
harness = false
